version: "3.8"
services:
  node:
    container_name: github-actions-env-toolkit-builder
    image: "node:20"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - GITHUB_REPOSITORY=ScientaNL/scienta
#      - GITHUB_REF=refs/heads/feature-develop/12344/34
      - GITHUB_REF=refs/tags/0.0.11-beta.2
      - GITHUB_SHA=f0425b578dfee4a9ea8e74d29027ef2d9d167997
    volumes:
      - ./:/home/node/app
    command: "tail -f /dev/null"
